apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
    - command: arlon bundle create xenial --tags test,xenial --desc "Xenial pod" --repo-url http://172.17.0.1:8188/myrepo.git --repo-path bundles/xenial
