apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 150
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    arlon-cluster: ec2-cluster
    arlon-profile: dynamic-1
    arlon-type: profile-app
    managed-by: arlon
  namespace: argocd
  name: ec2-cluster-profile-dynamic-1
status:
  health:
    status: Healthy
