# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

before:
  hooks:
    - make fmt
    - make vet
builds:
  - id: 'cli'
    ldflags:
      - -X github.com/arlonproj/arlon/cmd/install.capiCoreProvider=cluster-api:v1.1.5
      - -X github.com/arlonproj/arlon/cmd/initialize.argocdGitTag=release-2.4
      - -X github.com/arlonproj/arlon/cmd/version.cliVersion=0.10.0
      - -w
      - -s
    env:
      - CGO_ENABLED=0x
    goos:
      - linux
      #      - windows # coming soon?
      - darwin
    goarch:
      - 'amd64'
      - '386'
      - 'arm64'
    ignore:
      - goos: 'darwin'
        goarch: '386'
      - goos: 'linux'
        goarch: 'arm'
        goarm: '7'
      - goarm: 'mips64'
      - gomips: 'hardfloat'
      - goamd64: 'v4'
    skip: false
    no_unique_dist_dir: true
    mod_timestamp: '{{ .CommitTimestamp }}'
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v{{ .Version }}'

archives:
  - id: 'cli'
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}'
    replacements:
      darwin: 'Darwin'
      linux: 'Linux'
      windows: 'Windows'
      386: 'i386'
      amd64: 'x86_64'
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'refactor'
      - 'minor fix'
      - 'cleanup'
