coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
github_checks:
  annotations: false


# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
