coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:
  layout: diff


# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
