# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Arlon - GitOps-based Fleet Management for Kubernetes
theme:
  name: material
  logo: images/pictogram_arlon-stroke.svg
  favicon: images/favicon-32x32.png  
  palette: 
    # Palette toggle for light mode
    - scheme: default
  font:
    text: Work Sans

plugins:
  - search
  - mkdocs_pymdownx_material_extras

extra:
  version:
    default: stable
    provider: mike

extra_javascript:
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
  
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.striphtml:
      strip_comments: true
      strip_js_on_attributes: false
  - pymdownx.superfences:
      custom_fences:
        # Mermaid diagrams
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      
nav:
    - Overview: 'README.md'
    - Design: 'design.md'
    - Installation: 'installation.md'    
    - Tutorial: 'tutorial.md'
    - How to contribute to Arlon: 'contributing.md'
    - Help with MkDocs: 'help.md'

# The default edit_uri is : edit/master/docs/
edit_uri: edit/main/docs/
repo_url: https://github.com/arlonproj/arlon
repo_name: arlonproj/arlon
