# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Arlon 
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

#  name: gitbook
#  name: 'rtd-dropdown'
#theme: ivory
repo_url: https://github.com/arlonproj/arlon
repo_name: arlonproj/arlon
