apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 3600
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  namespace: ec2-cluster
status:
  controlPlaneReady: true
  infrastructureReady: true
  phase: Provisioned
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  namespace: ec2-cluster
status:
  phase: Running
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  namespace: ec2-cluster
status:
  ready: true
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  namespace: ec2-cluster
status:
  ready: true