apiVersion: arlon.io/v1
kind: ClusterRegistration
metadata:
  name: {{ .Values.global.clusterName }}
  namespace: {{ .Values.global.clusterName }}
spec:
  clusterName: {{ .Values.global.clusterName }}
  kubeconfigSecretName: {{ .Values.global.clusterName }}-kubeconfig
  kubeconfigSecretKeyName: {{ .Values.global.kubeconfigSecretKeyName }}

