apiVersion: v1
kind: Pod
metadata:
  labels:
    run: xenial
  name: xenial
  namespace: default
spec:
  containers:
  - command:
    - bash
    - -c
    - while true; do echo `date`; sleep 5; done
    image: ubuntu:xenial
    imagePullPolicy: IfNotPresent
    name: xenial
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
