apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 600
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ec2-cluster-xenial
  namespace: argocd
status:
  health:
    status: Healthy