apiVersion: apps/v1
kind: Deployment
metadata:
  name: arlon-webhook
  namespace: arlon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: arlon-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: arlon-webhook
    spec:
      containers:
      - command:
        - /arlon
        - webhook
        image: ghcr.io/arlonproj/arlon/controller:0.9.0
        imagePullPolicy: Always
        name: arlon-webhook
        ports:
        - containerPort: 9443
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
