# permissions for end users to edit appprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appprofile-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: arlon
    app.kubernetes.io/part-of: arlon
    app.kubernetes.io/managed-by: kustomize
  name: appprofile-editor-role
rules:
- apiGroups:
  - core.arlon.io
  resources:
  - appprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.arlon.io
  resources:
  - appprofiles/status
  verbs:
  - get
