# permissions for end users to view callhomeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: callhomeconfig-viewer-role
rules:
- apiGroups:
  - core.arlon.io
  resources:
  - callhomeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.arlon.io
  resources:
  - callhomeconfigs/status
  verbs:
  - get
