apiVersion: core.arlon.io/v1
kind: Cluster
metadata:
  name: example-1
  namespace: arlon
  annotations:
    arlon.io/profiles: frontend,backend
spec:
  clusterTemplate:
    url: https://github.com/arlonproj/arlon.git
    path: examples/clustertemplates/eks-managed-mpool
    revision: v0.10
