apiVersion: core.arlon.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: arlon
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: arlon
  name: cluster-sample
spec:
  # TODO(user): Add fields here
