apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    arlon-type: application
    managed-by: arlon
  name: redis
  namespace: argocd
spec:
  generators:
  - list:
      elements: []
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  template:
    metadata:
      name: '{{cluster_name}}-app-redis'
    spec:
      destination:
        namespace: default
        server: '{{cluster_server}}'
      project: default
      source:
        path: charts/bitnami/redis
        repoURL: https://github.com/bitnami
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
