apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.global.clusterName }}
  namespace: {{ .Values.global.clusterName }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {{ .Values.global.podCidrBlock }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ .Values.global.clusterName }}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: {{ .Values.global.clusterName }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: {{ .Values.global.clusterName }}
  namespace: {{ .Values.global.clusterName }}
spec:
  region: {{ .Values.global.region }}
  sshKeyName: {{ .Values.global.sshKeyName }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.global.clusterName }}-control-plane
  namespace: {{ .Values.global.clusterName }}
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: {{"'{{ ds.meta_data.local_hostname }}'"}}
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: {{"'{{ ds.meta_data.local_hostname }}'"}}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSMachineTemplate
      name: {{ .Values.global.clusterName }}-control-plane
  replicas: 3
  version: {{ .Values.global.kubernetesVersion }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane
  namespace: {{ .Values.global.clusterName }}
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: {{ .Values.global.nodeType }}
      sshKeyName: {{ .Values.global.sshKeyName }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Values.global.clusterName }}-md-0
  namespace: {{ .Values.global.clusterName }}
spec:
  clusterName: {{ .Values.global.clusterName }}
  replicas: {{ .Values.global.nodeCount }}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Values.global.clusterName }}-md-0
      clusterName: {{ .Values.global.clusterName }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: {{ .Values.global.clusterName }}-md-0
      version: {{ .Values.global.kubernetesVersion }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-md-0
  namespace: {{ .Values.global.clusterName }}
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: {{ .Values.global.nodeType }}
      sshKeyName: {{ .Values.global.sshKeyName }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.global.clusterName }}-md-0
  namespace: {{ .Values.global.clusterName }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: {{"'{{ ds.meta_data.local_hostname }}'"}}
