name: Unit Tests and Build

on:
  push:
    branches:
      - main
      - v0.3
      - v0.9
      - v0.10
  pull_request:
    branches:
      - main
      - v0.3
      - v0.9
      - v0.10

jobs:
  lint:
    environment: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Print the version of golang
        run: go version
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          skip-pkg-cache: true
          args: --timeout=10m
  build_and_unit_test:
    environment: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Print the version of golang
        run: go version
      - name: Run unit tests with code coverage
        run: make test
      - name: Build
        run: make build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./cover.out
