name: Go

on:
  push:
    branches:
      - main
      - v0.3
      - v0.9
  pull_request:
    branches:
      - main
      - v0.3
      - v0.9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3
        check-latest: true
        cache: true
    - name: Build
      run: go build -v ./...
    - name: Unit tests
      run: go test ./pkg/...
    - name: Run coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force
