name: Go

on:
  push:
    branches:
      - main
      - v0.3
      - v0.9
  pull_request:
    branches:
      - main
      - v0.3
      - v0.9

jobs:
  build:
    environment: arlon
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        token: ${{ secrets.GH_PAT }}
        go-version: 1.19
        check-latest: true
        cache: true
    - name: Print the version of golang
      run: go version
    - name: Build
      run: make build
    - name: Run unit tests with code coverage
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          token: ${{ secrets.GH_PAT }}
          check-latest: true
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: '**/requirements.txt'
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force
